[platformio]
default_envs = lilygo_pump_pb1

[env:lilygo_pump_pb1]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = time, log2file
build_flags = -Wall -Wextra
